### ISSUE TITLE
Small artifacts in HDR Image

### ISSUE THREAD

**Issue by tobiasmueller14** [SSARCandy/HDR-imaging#3]
In the resuting .hdr image are cyan or magenta colored pixels. Are there parameters wrong or is there an issue with the calculations? I tried diffrent hdr viewer and tonemapper, all witrh the same result.

![artifacts](https://user-images.githubusercontent.com/62502003/89493405-5cd88400-d7b4-11ea-8b6b-2a5c78a3ea6f.png)

**Comment by SSARCandy** [comment]
it is due to tonemapper, not hdr itself. you can refer to the radiance map in my ipython notebook https://github.com/SSARCandy/HDR-imaging/blob/master/HDR-playground.ipynb
It doesn't have those artifacts.

**Comment by tobiasmueller14** [comment]
OK, can you recommend a suitable tonemapper or parameters? Only for the meomrial image with lambda = 50.
Thank you

**Comment by tobiasmueller14** [comment]
https://ssarcandy.tw/2017/04/16/High-Dynamic-Range-Imaging/ there are the same artifacts. How can you know that the hdr itself does not have them?

**Comment by SSARCandy** [comment]
yes, in my post, the result (tonemapped) have artifacts also, it is still about tonemapping issue. it is not a easy task when converting HDR to SDR. You may need to implement other tonemap algorithms for this.

> How can you know that the hdr itself does not have them?

Because of the HDR radiance map didn't have those unnormal noises, I still tend to believe the issue is due to tonemap algorithm.

**Comment by ssdutHB** [comment]
> yes, in my post, the result (tonemapped) have artifacts also, it is still about tonemapping issue. it is not a easy task when converting HDR to SDR. You may need to implement other tonemap algorithms for this.
> 
> > How can you know that the hdr itself does not have them?
> 
> Because of the HDR radiance map didn't have those unnormal noises, I still tend to believe the issue is due to tonemap algorithm.

When I directly passed the hdr array to tone mapping functions implemented in cv2, the result looked good. But if I saved the array mentioned above as .hdr file with the function save_hdr, and read the image and applied the tone mapping again, there were artifacts. So, It is clear that the save_hdr function leads to the artifacts. And substituting the save_hdr function with cv2.imwrite("res.hdr", hdr) sovle the problem.

**Comment by SSARCandy** [comment]
thank you for your research, I'll dig into it
